README.md

스터디 스케쥴 및 준비물 수정

---

김명환/20191005_Docker.md

1. Docker 설치
2. Dockerfile 을 통한 이미지파일 빌드 및 실행
3. Docker private registry 생성 후 push, pull 테스트

20191005_Docker 실습결과

---

README.md

Update schedule and study contents

---

anon/Dockerfile
anon/webserver.js

This example code is going to be executed in the container.

NodeJS webserver example

---

anon/Dockerfile
anon/README.md
anon/boot/cmdline.txt
anon/etc/docker/daemon.json

Docker 및 kubernetes 관련 추가

---

김명환/20191005_Docker.md
김명환/20191013_k8s_master and worker node_init.md

실습내용
1. 쿠버네티스 설치(우분투 18.04 LTS 환경)
2. 마스터 및 슬레이브(워커) 노드 초기화
구글에서 제공하는 참고문서를 통해 초기화하는 것 까지 진행해봤는데 Pod network에 대한 개념이 제대로 안잡히네요....ㅠ 오프라인 모임전까지 anon 님이 올려주신 내용 참고해서 숙지해오겠습니다!

20191013_쿠버네티스 설치 및 초기화 실습

---

anon/README.md
anon/etc/default/dnsmasq
anon/etc/network/interfaces.d/eth0

DNS service 설정 (dnsmasq)

---

anon/README.md

Update document (format).

---

README.md

Github 사용법 갱신

---

김명환/20191013_k8s_master and worker node_init.md

Update 20191013_k8s_master and worker node_init.md

---

README.md
anon/README.md

Round 1,2,3 업데이트

---

anon/README.md

Docker Private Registry 설정 추가

---

anon/Dockerfile
anon/README.md
anon/deploy.yaml

registry container 의 shell 을 띄우면 찾을 수 있습니다.

Docker registry 의 저장소 위치 확인

---

anon/dashboard/README.md
anon/dashboard/admin-user.yaml
anon/dashboard/dashboard-ingress.yaml
anon/dashboard/role-binding.yaml

Kubernetes dashboard 추가

---

anon/ingress/README.md
anon/ingress/hello-world-ingress.yaml
anon/ingress/service.yaml

Ingress controller 예제

---

anon/deployment-deployment.yaml
anon/pod-deployment.yaml
anon/service-deployment.yaml

Add examples for creating pod, deployment, service

---

anon/dashboard/dashboard-ingress.yaml
anon/ingress/hello-world-ingress.yaml
anon/service-deployment.yaml

Fix hello-world service ingress & deployments

---

publish/Makefile
publish/README.md
publish/References.bib
publish/ap.tex
publish/cloudy.tex
publish/docker.tex
publish/kubernetes.tex

Initiate the documents

---

publish/docker/docker_install.txt

ubuntu 18.04 LTS 환경에서 docker 설치하는 방법을 메뉴얼로 간략하게 작성하였습니다.
자세한 설명부분은 추후에 더 업데이트 하겠습니다.

add docker install manual

---

publish/k8s/20191119_쿠버네티스 문서_v1.txt
publish/k8s/20191122_kubernetes_v2.txt

금일 쿠버네티스를 위한 기본 환경 설정까지 마쳤으며,  마스터 노트 클러스터 환경 구성에서 이슈가 발생하여 여기서 멈췄습니다. 다음 주까지 이슈 해결 및 다음 과정 이어서 진행하겠습니다.

add k8s 설치 환경 및 메뉴얼

---

publish/docker/docker_node_web_build.md
publish/docker/docker_private_registry_for_dockerhub.md
publish/docker/docker_user_manual.md

docker 에 node.js 를 통해 간단한 웹 서버 구축 메뉴얼을 작성했습니다.
상세내용은  추후에 정리하겠습니다.

add  "Build node.js web server through docker" manual
